Bump parent pom and Jenkins to 1.645
Adds plugins detached from Jenkins core

Adds Eclipse sisu as managed dependency due to:
> java.lang.IncompatibleClassChangeError: Implementing class